export { default as DashboardLayout } from './DashboardLayout'
export { default as Landing } from './Landing'
export { default as HomeLayout } from './HomeLayout'
export { default as Register } from './Register'
export { default as Login } from './Login'
export { default as Error } from './Error'
export { default as AddItems } from './AddItems'
export { default as AddBankDetails, } from './AddBankDetails'
export { default as ViewBankDetails, } from './ViewBankDetails'
export { default as AllItems } from './AllItems'
export { default as Dashboard } from './Dashboard'
export { default as DeleteJob } from './DeleteItem'
export { default as EditItems } from './EditItems'
export { default as Profile } from './Profile'
export { default as Admin } from './Admin'
export {default as AdminDashboard} from './AdminDashboard'




export {default as AdminDashbordLayout } from './AdminDashbordLayout'
export {default as AdminDashbord } from './Dashbord'
export {default as Request } from './Request'
export {default as Staf } from './Staf'
export {default as Company } from './Company'
export {default as Item } from './Item'
export {default as Transaction } from './Transaction'
export {default as Vehicle } from './Vehicle'
export {default as Route } from './Route'
export {default as AddRoute } from './AddRoute'
export {default as Test } from './Test'

